version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - server
    ports:
      - "3001:3001" #EDIT
    volumes:
      - ./client:/app
      - /app/node_modules
    scale: 2 # Number of client instances
